### ISSUE TITLE
tab key 입력에 따른 interaction 구현

### ISSUE THREAD

**Issue by domino8788** [boostcamp-2020/Project18-C-Bootion#100]
# tab key 입력에 따른 interaction 구현

- tab 키 입력 시 현재 focus된 블록이 이전 형제 블록의 children에 삽입되도록 구현한다.

## 완료 조건 ✅

- [ ] 현재 focus된 블록을 이전 형제 블록의 children에 삽입하는 로직을 구현한다.
  - [ ] focus 된 블록의 부모에서 focus된 블록을 제거하도록 한다.

## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by YiSoJeong** [comment]
![tab](https://user-images.githubusercontent.com/37685690/102721646-729fad80-433f-11eb-8165-0595317b5723.gif)
![shiftTab](https://user-images.githubusercontent.com/37685690/102721647-74697100-433f-11eb-93a1-a6a5775d07be.gif)
