### ISSUE TITLE
backspace 입력에 따른 interaction 구현

### ISSUE THREAD

**Issue by domino8788** [boostcamp-2020/Project18-C-Bootion#101]
# backspace 입력에 따른 interaction 구현

- backspace 입력 시 focus 된 블록이 삭제되게 한다.

## 완료 조건 ✅

- [ ] backspace 입력 시 focus 된 블록이 삭제되게 한다.
- [ ] block을 삭제하는 로직을 구현한다.
- [ ] type이 text가 아닌 블록은 type이 text가 되게한다.

## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by YiSoJeong** [comment]
![backspace](https://user-images.githubusercontent.com/37685690/102721591-176dbb00-433f-11eb-9168-720afefc7da6.gif)
