### ISSUE TITLE
enter key 입력 시 새로운 블록을 생성하는 interaction 구현

### ISSUE THREAD

**Issue by domino8788** [boostcamp-2020/Project18-C-Bootion#74]
# enter key 입력 시 새로운 블록을 생성하는 interaction 구현

## 완료 조건 ✅

- [x] 기존 enter key 동작을 막는다.
- [x] enter key 입력시 focus된 블록의 다음 위치에 새로운 블록을 생성하는 로직을 구현한다.

## 관련 이슈 📎

관련 이슈 없음

## 레퍼런스 📚

레퍼런스 없음

**Comment by YiSoJeong** [comment]
![Enter](https://user-images.githubusercontent.com/37685690/102721569-fb6a1980-433e-11eb-994d-74674b94e0e8.gif)
